---
deployment:
      tasks:
       - export DEPLOYPATH=/home/restroworld/public_html/
       - export REPOPATH=/home/restroworld/repositories/Restroworld-Frontend
       - /bin/chmod 755 ${DEPLOYPATH}
       - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
       - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
       - /bin/rsync -aP --progress ${REPOPATH}/ ${DEPLOYPATH} 
       - /bin/cp -R dist/* $DEPLOYPATH
